version: "3"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        environment:
            - PG_HOST=database
        depends_on:
            - database

    database: # THIS IS THE SERVICES NAME THAT YOU NEED TO USE AS THE HOST VALUE SO THAT IT FINDS THE CONTAINER?
        image: postgres:latest
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

        ports:
            - "5432:5432"
        # volumes:d
        #     - ./database:/docker-entrypoint-initdb.d # Finds my database folder and mounts it into the container. Only works with SQL script.
